trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'blob'
    publishLocation: 'Container'